# Generated by Django 3.2.23 on 2025-10-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pictures',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
