# Generated by Django 4.2.25 on 2025-11-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pictures',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
