# Generated by Django 3.1.12 on 2025-09-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250930_1015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
