# Generated by Django 4.2.25 on 2025-11-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_profile_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pictures',
            field=models.ImageField(default='default.png/', upload_to=''),
        ),
    ]
